apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: identity-socializer-luiscusihuaman
  name: next-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next-app
  template:
    metadata:
      labels:
        app: next-app
        stack.okteto.com/name: backoffice
        stack.okteto.com/service: next-app
    spec:
      containers:
        - name: next-app
          image: $OKTETO_BUILD_NEXT_APP_IMAGE
          imagePullPolicy: Always
          env:
            - name: NEXTAUTH_URL
              value: http://localhost:3000
            - name: NEXTAUTH_SECRET
              value: 'dada' # Add your secret here
            - name: GITHUB_ID
              value: 'dada' # Add your GitHub ID here
            - name: GITHUB_SECRET
              value: 'dad' # Add your GitHub Secret here
            - name: NEXT_PUBLIC_FIREBASE_API_KEY
              value: 'AIzaSyC5HA-fJkTK-JBgzZxad93JQNbR8igQ-Ns'
            - name: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
              value: 'admin-c3f90.firebaseapp.com'
            - name: NEXT_PUBLIC_FIREBASE_PROJECT_ID
              value: 'admin-c3f90'
            - name: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
              value: 'admin-c3f90.appspot.com'
            - name: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
              value: '734188578902'
            - name: NEXT_PUBLIC_FIREBASE_APP_ID
              value: '1:734188578902:web:a2e9d7d5ce9a6728b133f'
            - name: NEXT_PUBLIC_ADMIN_TOKEN
              value: 'adminToken'
            - name: NEXT_PUBLIC_API_URL
              value: 'https://apigw-apigw-luiscusihuaman.cloud.okteto.net/gateway/route'
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: identity-socializer-luiscusihuaman
  name: next-app
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app: next-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
