version: '3'

services:
  next-app:
    container_name: next-app
    build:
      context: ../next-app
      dockerfile: ../next-app/prod.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    env_file:
      - ../next-app/.env.remote
    restart: always
    ports:
      - 3000:3000
    networks:
      - microservices

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  microservices:
    external: true
